### PR TITLE
Merge from upstream + Implement async load for audio

### PR DESCRIPTION
**Pull request by Mefiresu**
This PR includes many bugfixes and improvements, along with support for Origins Plus stuff in Legacy mode, coming from upstream.

Last commit in the list also implements async load for audio using `std::thread` to reduce stutters during gameplay.

### CODE REVIEW

**Comment by btarg** [comment]
Is this still WIP? I would love to compile the game for my N3DS on Windows with the latest features

**Comment by Sparkygan** [comment]
curse myself for choosing to buy an old 3ds

**Comment by c08oprkiua** [comment]
> curse myself for choosing to buy an old 3ds

If RSDKv5 is anything like RSDKv3, it should be totally possible to implement a citro2D based graphics backend to achieve playable if not full speed on O3DS

**Comment by Sparkygan** [comment]
I found a build somewhere that runs, admittedly at like a third of the speed, but it runs. So excited for when they do this though

**Comment by Sonic20125** [comment]
> I found a build somewhere that runs, admittedly at like a third of the speed, but it runs. So excited for when they do this though

Well, don't be stingy. Where can we find it?

**Comment by Sparkygan** [comment]
I **THINK** it's this one, as I recall the cia version doesen't work, but the 3dsx one will
https://gbatemp.net/goto/post?id=10075895

**Pull request merged**
