### PR TITLE
add build guide and workflow

### PR DESCRIPTION
**Pull request by liaminventions**

### CODE REVIEW

**Comment by liaminventions** [comment]
done. it should compile on pushes and pull requests

**Comment by liaminventions** [comment]
actually one sec - i gotta fix the audio codec defs

**Comment by liaminventions** [comment]
Ok. This is ready to be merged now.
The guide is from https://github.com/MisterSheeple/Sonic-Mania-3DS-Build-Guide

**Comment by SaturnSH2x2** [comment]
Sorry, just seeing this now lol

One thing; did you set `AUTOBUILD=1`? Doing so is needed to disable the Plus DLC while building. Autobuilds shouldn't include Plus DLC, at the request of the decomp devs.  There's no way to reasonably verify that the user actually bought said DLC with the decomp; the idea is users should have to compile the decomp/port manually in order to use the DLC.

**Comment by liaminventions** [comment]
Ah, right. I'll fix this once I get to my computer...

**Comment by liaminventions** [comment]
ok, this should be ready now.

**Pull request merged**
